from __future__ import annotations

from typing import Any, Literal, TypedDict

from src.app.multi_agent.researcher import run_deterministic_research
from src.app.multi_agent.state import (
    MultiAgentArtifact,
    MultiAgentState,
    MultiAgentTask,
    create_multi_agent_artifact,
    create_multi_agent_event,
    create_multi_agent_task,
)


ToolActionType = Literal[
    "inspect_state",
    "summarize_research",
    "prepare_implementation_plan",
    "prepare_validation_plan",
]


class ToolExecutionRecord(TypedDict):
    action_type: ToolActionType
    title: str
    status: str
    input_summary: str
    output_summary: str
    evidence: list[str]


class ToolAgentOutput(TypedDict):
    tool_role: str
    planning_mode: str
    objective: str
    source_task_id: str
    execution_records: list[ToolExecutionRecord]
    constraints_checked: list[str]
    next_role: str | None
    execution_boundary: str
    llm_used: bool
    external_tools_used: bool
    note: str


def _find_pending_tool_task(state: MultiAgentState) -> MultiAgentTask | None:
    for task in state.get("tasks", []):
        if task.get("assigned_role") == "tool" and task.get("status") == "pending":
            return task
    return None


def _find_next_pending_role_after_tool(state: MultiAgentState) -> str | None:
    for task in state.get("tasks", []):
        if task.get("assigned_role") == "tool":
            continue
        if task.get("status") == "pending":
            return task.get("assigned_role")
    return None


def _ensure_tool_task(
    state: MultiAgentState,
    *,
    objective: str,
    planning_mode: str,
) -> MultiAgentTask:
    tool_task = _find_pending_tool_task(state)
    if tool_task is not None:
        return tool_task

    tool_task = create_multi_agent_task(
        title="Execute deterministic tool step",
        description=f"Execute deterministic tool simulation for: {objective}",
        assigned_role="tool",
        status="pending",
        metadata={
            "created_by": "tool_fallback",
            "planning_mode": planning_mode,
            "reason": "Planner output did not contain a pending tool task.",
        },
    )
    state["tasks"].append(tool_task)
    state["events"].append(
        create_multi_agent_event(
            event_type="task_added",
            role="tool",
            message="Tool Agent added fallback tool task.",
            metadata={
                "task_id": tool_task["task_id"],
                "planning_mode": planning_mode,
            },
        )
    )
    return tool_task


def _build_tool_execution_records(
    *,
    objective: str,
    planning_mode: str,
    state: MultiAgentState,
) -> list[ToolExecutionRecord]:
    tasks = state.get("tasks", [])
    artifacts = state.get("artifacts", [])
    memory = state.get("memory", {})

    role_counts: dict[str, int] = {}
    status_counts: dict[str, int] = {}

    for task in tasks:
        role = task.get("assigned_role", "unknown")
        status = task.get("status", "unknown")
        role_counts[role] = role_counts.get(role, 0) + 1
        status_counts[status] = status_counts.get(status, 0) + 1

    records: list[ToolExecutionRecord] = [
        {
            "action_type": "inspect_state",
            "title": "Inspect Multi-Agent state",
            "status": "completed",
            "input_summary": "Read Day54 state produced by Planner and Researcher.",
            "output_summary": "State contains planner memory, researcher memory, task assignments, and artifacts for downstream execution.",
            "evidence": [
                f"objective={objective}",
                f"planning_mode={planning_mode}",
                f"task_count={len(tasks)}",
                f"artifact_count={len(artifacts)}",
                f"role_counts={role_counts}",
                f"status_counts={status_counts}",
            ],
        },
        {
            "action_type": "summarize_research",
            "title": "Summarize researcher findings",
            "status": "completed",
            "input_summary": "Read memory['researcher'] generated by Day54.",
            "output_summary": "Researcher findings are available and can be converted into a deterministic implementation boundary.",
            "evidence": [
                f"researcher_memory_exists={'researcher' in memory}",
                f"research_finding_count={len(memory.get('researcher', {}).get('findings', []))}",
                "No external research or LLM call was used.",
            ],
        },
        {
            "action_type": "prepare_implementation_plan",
            "title": "Prepare deterministic implementation result",
            "status": "completed",
            "input_summary": "Use planner task and researcher findings to simulate the Tool Agent execution result.",
            "output_summary": "Tool Agent produced a CI-safe execution artifact without editing repository files or running shell commands.",
            "evidence": [
                "external_tools_used=false",
                "filesystem_modified=false",
                "shell_commands_executed=false",
            ],
        },
        {
            "action_type": "prepare_validation_plan",
            "title": "Prepare downstream validation handoff",
            "status": "completed",
            "input_summary": "Identify what the future Critic Agent should validate.",
            "output_summary": "Future Critic Agent should verify task status transitions, event boundaries, memory output, artifact output, and graph_fusion default safety.",
            "evidence": [
                "Critic Agent is not executed in Day55.",
                "Supervisor graph is not started in Day55.",
                "graph_fusion remains non-default.",
            ],
        },
    ]

    return records


def _render_tool_artifact(
    *,
    objective: str,
    planning_mode: str,
    tool_task: MultiAgentTask,
    execution_records: list[ToolExecutionRecord],
) -> str:
    lines = [
        "# Deterministic Tool Execution Notes",
        "",
        f"Objective: {objective}",
        f"Planning mode: {planning_mode}",
        f"Tool task: {tool_task['title']}",
        f"Tool task id: {tool_task['task_id']}",
        "",
        "## Execution records",
        "",
    ]

    for index, record in enumerate(execution_records, start=1):
        lines.extend(
            [
                f"{index}. {record['title']}",
                f"   - action_type: {record['action_type']}",
                f"   - status: {record['status']}",
                f"   - input: {record['input_summary']}",
                f"   - output: {record['output_summary']}",
                "",
            ]
        )

    lines.extend(
        [
            "## Boundary",
            "",
            "- Tool Agent is deterministic and LLM-free.",
            "- Tool Agent does not execute real shell commands in Day55.",
            "- Tool Agent does not modify repository files in Day55.",
            "- Critic / Supervisor graph are not executed in Day55.",
            "- graph_fusion remains a non-default retrieval backend.",
        ]
    )

    return "\n".join(lines)


def run_deterministic_tool_agent(
    task: str,
    *,
    thread_id: str,
    trace_id: str,
    metadata: dict[str, Any] | None = None,
) -> MultiAgentState:
    state = run_deterministic_research(
        task=task,
        thread_id=thread_id,
        trace_id=trace_id,
        metadata=metadata,
    )

    planner_memory = state["memory"]["planner"]
    planning_mode = planner_memory["planning_mode"]

    tool_task = _ensure_tool_task(
        state=state,
        objective=task,
        planning_mode=planning_mode,
    )

    state["current_role"] = "tool"
    state["status"] = "pending"

    tool_task["status"] = "running"
    state["events"].append(
        create_multi_agent_event(
            event_type="task_started",
            role="tool",
            message="Tool Agent started deterministic tool execution.",
            metadata={
                "task_id": tool_task["task_id"],
                "planning_mode": planning_mode,
                "llm_used": False,
                "external_tools_used": False,
            },
        )
    )

    execution_records = _build_tool_execution_records(
        objective=task,
        planning_mode=planning_mode,
        state=state,
    )

    tool_task["status"] = "completed"
    tool_task["result"] = "Deterministic Tool Agent produced tool execution records and an execution artifact."
    tool_task["metadata"] = {
        **tool_task.get("metadata", {}),
        "tool_completed": True,
        "execution_record_count": len(execution_records),
        "llm_used": False,
        "external_tools_used": False,
        "filesystem_modified": False,
        "shell_commands_executed": False,
    }

    next_role = _find_next_pending_role_after_tool(state)

    tool_output: ToolAgentOutput = {
        "tool_role": "tool",
        "planning_mode": planning_mode,
        "objective": task,
        "source_task_id": tool_task["task_id"],
        "execution_records": execution_records,
        "constraints_checked": [
            "Tool Agent is deterministic and LLM-free.",
            "Tool Agent does not execute real shell commands in Day55.",
            "Tool Agent does not modify repository files in Day55.",
            "Critic / Supervisor graph are not executed in Day55.",
            "graph_fusion remains a non-default retrieval backend.",
        ],
        "next_role": next_role,
        "execution_boundary": "tool_simulation_only",
        "llm_used": False,
        "external_tools_used": False,
        "note": "Day55 executes only the deterministic Tool Agent step on top of Day54 Researcher state flow.",
    }

    state["memory"]["tool"] = tool_output

    tool_artifact: MultiAgentArtifact = create_multi_agent_artifact(
        name="deterministic_tool_execution_notes",
        artifact_type="markdown",
        content=_render_tool_artifact(
            objective=task,
            planning_mode=planning_mode,
            tool_task=tool_task,
            execution_records=execution_records,
        ),
        created_by="tool",
        metadata={
            "planning_mode": planning_mode,
            "source_task_id": tool_task["task_id"],
            "execution_record_count": len(execution_records),
            "llm_used": False,
            "external_tools_used": False,
        },
    )
    state["artifacts"].append(tool_artifact)

    state["events"].append(
        create_multi_agent_event(
            event_type="artifact_added",
            role="tool",
            message="Tool Agent added deterministic execution artifact.",
            metadata={
                "artifact_id": tool_artifact["artifact_id"],
                "artifact_type": tool_artifact["artifact_type"],
                "source_task_id": tool_task["task_id"],
            },
        )
    )

    state["events"].append(
        create_multi_agent_event(
            event_type="task_completed",
            role="tool",
            message="Tool Agent completed deterministic tool execution.",
            metadata={
                "task_id": tool_task["task_id"],
                "planning_mode": planning_mode,
                "execution_record_count": len(execution_records),
                "llm_used": False,
                "external_tools_used": False,
            },
        )
    )

    return state